version: '3'

services:
  # Frontend Service
  frontend:
    image: node:latest  # Using the latest Node.js image
    container_name: home_control_frontend
    restart: always
    volumes:
      - ./frontend:/app  # Mount your local frontend directory to the container
    working_dir: /app
    ports:
      - "3000:3000"  # Expose port 3000 to access the React app
    command: sh -c "npm install && npm start"
    depends_on:
      - backend

  # Backend Service
  backend:
    image: node:latest
    container_name: home_control_backend
    restart: always
    volumes:
      - ./backend:/app  # Mount your local backend directory to the container
    working_dir: /app
    ports:
      - "5000:5000"  # Expose port 5000 for the Express.js backend API
    command: sh -c "npm install && node app.js"
    depends_on:
      - db
      # - mqtt

  # PostgreSQL Database Service
  db:
    image: postgres:latest
    container_name: home_control_db
    restart: always
    volumes:
      - postgres_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=KPqMh8Xg8KCnjqvSDnt3
    ports:
      - "5432:5432"

  # MQTT Broker Service (Eclipse Mosquitto)
  # mqtt:
  #   image: eclipse-mosquitto:latest
  #   container_name: home_control_mqtt
  #   ports:
  #     - "1883:1883"  # MQTT protocol port
  #     - "9001:9001"  # Websockets port
  #   volumes:
  #     - mosquitto_config:/mosquitto/config
  #     - mosquitto_data:/mosquitto/data
  #     - mosquitto_log:/mosquitto/log

volumes:
  postgres_db:
    driver: local
  # mosquitto_config:
  # mosquitto_data:
  # mosquitto_log:

